### ISSUE TITLE
Rendering CUB dataset to 3D? 

### ISSUE THREAD

**Issue by felixboevr** [nv-tlabs/DIB-R#10]
How can I render single images from the CUB dataset and visualize it in 3D as described in the paper? thanks

**Comment by Atharex** [comment]
The model itself seems to be missing... /checkpoints/g_model.pth

And also an explanation for this structure, like where we need to run the train-all.py command from and what are these command line options supposed to be (test_list.txt for instance)

 --g_model_dir ./checkpoints/g_model.pth \
 --svfolder ./prediction \
 --data_folder ./dataset \
 --filelist ./test_list.txt

Any estimates, when the full tutorial will be released?

**Comment by wenzhengchen** [comment]
Hi, due to some copyright issues, we didn't release the model. I am coordinating with the lawyer and will release it soon. Maybe in 2 weeks.

**Comment by aluo-x** [comment]
@wenzhengchen Thanks for the code release so far! Have there been any updates regarding the release of the complete code base?

**Comment by bmccallister** [comment]
I am reiterating the above's desirer for the pth file!  I would love to begin playing with this toolset.

**Comment by imnik11** [comment]
> I am reiterating the above's desirer for the pth file! I would love to begin playing with this toolset.

Thanks for building toolset!
where can I find that toolset?
