### ISSUE TITLE
How to get depth from DIB renderer?

### ISSUE THREAD

**Issue by wangg12** [nv-tlabs/DIB-R#12]
Now it only supports color and mask, how can I get depth?

**Comment by wenzhengchen** [comment]
Hi, sorry for the delay.
To get depth it is very simple. You can simply replace the color, which is bxvx3(batch, vertex num, rgb 3channel), to depth, which is bxvx1 (batch, vertex num, depth value). Note that we support features with any channel number. It doesn't matter that it is a 3 channel rgb value or a 1 channel depth value.

**Comment by wangg12** [comment]
@wenzhengchen Do you mean that I need to transform the coordinates to the camera space to get depth values for each vertex first and then run the renderer in two passes to get both color and depth image? Should the depth values be normalized between [0,1]? Because usually in OpenGL the color attributes must be in [0,1].
