### ISSUE TITLE
pip install requirements not working

### ISSUE THREAD

**Issue by IOTeule** [nv-tlabs/DIB-R#13]
Dear  All,

2 points, 

**a)** there is a typo in the  README cmd, should be pip install -r requirements.txt.
**b)** pip fails at torch
ERROR: Could not find a version that satisfies the requirement torch==1.1.0 (from -r requirements.txt (line 3)) (from versions: 0.1.2, 0.1.2.post1, 0.1.2.post2)
ERROR: No matching distribution found for torch==1.1.0 (from -r requirements.txt (line 3))

PIP version:
pip 20.0.1 from c:\users\me\appdata\local\programs\python\python37-32\lib\site-packages\pip (python 3.7)

**Comment by IOTeule** [comment]
Just seen this, so a user warning would have been helpful.
https://github.com/pytorch/pytorch/issues/29395

**Comment by IOTeule** [comment]
need support for this, tried to install PyTorch without success.
Please translate the below into a simple command to make things run, thx.

pip OS:Windows Package: Pip and CUDA: None ??

Copied from here (https://pytorch.org/get-started/locally/#no-cuda-1)

> pip
> No CUDA
> To install PyTorch via pip, and do not have a CUDA-capable system or do not require CUDA, in the above selector, choose OS: Windows, Package: Pip and CUDA: None. Then, run the command that is presented to you.
> 
> With CUDA
> To install PyTorch via pip, and do have a CUDA-capable system, in the above selector, choose OS: Windows, Package: Pip and the CUDA version suited to your machine. Often, the latest CUDA version is better. Then, run the command that is presented to you.

**Comment by athanggupte** [comment]
@IOTeule I had the same issue while installing PyTorch. Assuming you are using Python 3.8, you can use the following: 
```bash
pip install torch==1.5.1+cpu torchvision==0.6.1+cpu -f https://download.pytorch.org/whl/torch_stable.html
```
Revert back if this does not work

**Comment by svlandeg** [comment]
Or try:
`pip install -r requirements.txt -f https://download.pytorch.org/whl/torch_stable.html`
