### ISSUE TITLE
Training on custom dataset

### ISSUE THREAD

**Issue by hamaadtahir** [nv-tlabs/DIB-R#17]
I have collected the images of some gadgets from internet, and now I want to train DIB-R on those images. How do I do that?

**Comment by wenzhengchen** [comment]
Sorry for the delay. First, you need to make sure you have an input image, a GT mask and the corresponding camera pose. Note that camera pose is needed!!!

Next what you do is simply run a network to predict 3D shape from the input image, render it back to a rendered image under the given camera pose, then compare with the input image and GT mask.  You can check Kaolin for the training script.
