### ISSUE TITLE
Unable to run project over Intel CPU

### ISSUE THREAD

**Issue by duliba** [nv-tlabs/DIB-R#19]
I'm trying to get this project up and running on my own Windows machine. I installed the dependencies, but was unable compile the DIB-Render as shown in the `README` because I have an Intel-based GPU (unsupported by NVIDIA's CUDA).

I thought to myself that maybe I can simply run the project on a CPU, and I saw in the `test-all.py` file that there seems to be some support for CPU-based machines in this project. From line 130:
```
device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')
```

However, when I tried to build the `cuda_dib_render` I realized that I must have CUDA on my machine. So it's not clear from the docs - do I have to have a CUDA-enabled GPU, or can I run this project on a normal Intel GPU? Or even a CPU?

If I have to run it over a CUDA-enabled GPU, do you have a recommended setup for a compatible machine on Google Cloud Platform? Would help a lot to future developers who want to test out this nice project by avoiding these early pitfalls.

Thanks!

**Comment by duliba** [comment]
We're doing this for a joint research in the Hebrew University and Bezalel Academy. Our goal is to publish a paper that builds on top of this project citing your work.

**Comment by wenzhengchen** [comment]
Hi, for now, dibr only supports cuda.
