### ISSUE TITLE
Render more than 3 channels?

### ISSUE THREAD

**Issue by ebartrum** [nv-tlabs/DIB-R#3]
Hey, thanks so much for this! For my use case I would like to render using a texture with more than 3 channels. It is not currently possible: 
"colors_bxfx3d must be same point size (dr_forward_batch at dr.cpp:90)"

Could you please make this feature available as an option?

**Comment by wenzhengchen** [comment]
Hi, it has been already supported.

colors_bxfx3d means this is a triangle mesh(f faces, each face has 3 vertices), each vertex has a d-dimension feature and d could be any number. If you have more than 3(rgb) channels, you can simply change different d and send your data to the render.

**Comment by ebartrum** [comment]
I have been using RenderMeshColor as the rendering class. It still only works with 3 channels, and the code mentions 3 colours at https://github.com/nv-tlabs/DIB-R/blob/611f69dce00e75f65b37722120010e2da46fc1bf/utils/render/renderfunc_cluster.py#L102

Should I be using a different class as the renderer?

**Comment by wenzhengchen** [comment]
HI, 

In fact, it is:

        # 3 colors, each color has d dimension feature.
        c0_bxfxd = tfcolor_bxpxd[:, faces_fx3[:, 0], :]
        c1_bxfxd = tfcolor_bxpxd[:, faces_fx3[:, 1], :]
        c2_bxfxd = tfcolor_bxpxd[:, faces_fx3[:, 2], :]
        tfcolor_bxfx3d = torch.cat((c0, c1, c2), dim=2)

where the tfcolor_bxpxd is your own data with any d.

**Comment by wenzhengchen** [comment]
https://github.com/nv-tlabs/DIB-R/blob/611f69dce00e75f65b37722120010e2da46fc1bf/dib-render/render_cuda/utils_render_color2.py#L71

Also, change the 3 to your own d.

I think we will update it soon. Maybe after CVPR supp DDL.

**Comment by ebartrum** [comment]
Thanks, I tried changing the 3 to d in both lines 70 and 71, it still doesnt work. Still getting: 
RuntimeError: (colors_bxfx3d.size(0) == bnum) && (colors_bxfx3d.size(1) == fnum) && (colors_bxfx3d.size(2) == 3 * dnum) ASSERT FAILED at dr.cpp:90, please report a bug to PyTorch. colors_bxfx3d must be same point size (dr_forward_batch at dr.cpp:90)

**Comment by wenzhengchen** [comment]
Hi, 

The reason why you got such error is that in below code:

https://github.com/nv-tlabs/DIB-R/blob/611f69dce00e75f65b37722120010e2da46fc1bf/dib-render/cuda_dib_render/dr.cpp#L80

we will check the dimension to make sure they match with each other.

BTW, in this code, we just release vertex color version, while we put the texture render part in kaolin. https://github.com/NVIDIAGameWorks/kaolin, which have more optimization and acceleration. You can also try it.

**Comment by ebartrum** [comment]
Thanks, it works!
