### ISSUE TITLE
Render faces on both sides

### ISSUE THREAD

**Issue by ebartrum** [nv-tlabs/DIB-R#4]
Is it possible to render faces with the texture on both sides of the face, ie both orientations?

**Comment by wenzhengchen** [comment]
Hi,

Are you saying we didn't draw clock-wise faces(faces not oriented to camera)? 

If you want, comment the code below, where we check face to only render one side face. 
https://github.com/nv-tlabs/DIB-R/blob/611f69dce00e75f65b37722120010e2da46fc1bf/dib-render/cuda_dib_render/dr_cuda_for.cu#L77

You need also to modify the code in back propagation and recompile it.

**Comment by ebartrum** [comment]
Exactly, thanks a lot! So I would also need to comment out the corresponding line from dr_cuda_back.cu? Which line would that be? I couldn't find a 'direction' variable in that file.

**Comment by wenzhengchen** [comment]
Hi, 

You do not need to modify backpropagation. This is because in backward process we handle face based on face index map(imidx_bxhxwx1). If you fill it in forward (no matter it is counterclockwise or clockwise), in backward it will be automatically calculated.
