### ISSUE TITLE
cofused about camera matrix

### ISSUE THREAD

**Issue by wuneng** [nv-tlabs/DIB-R#5]
https://github.com/nv-tlabs/DIB-R/blob/611f69dce00e75f65b37722120010e2da46fc1bf/utils/render/renderfunc_cluster.py#L34
Given the focal length f_x, f_y and the principal point c_x, c_y from a camera calibration matrix, how to get rot, pose and proj matrix?

**Comment by wenzhengchen** [comment]
Hi, 

I am not sure which coordinate system you are talking about. But the answer is that you can not get rot, pose matrix just from f_x, f_y, c_x, c_y. They are used to convert points in camera plane coordinate to pixel coordinate.
