### ISSUE TITLE
Inference time

### ISSUE THREAD

**Issue by hungsing92** [nv-tlabs/DIB-R#7]
Hi,

 Many thanks for your work.!

I use your lib to render a image, but it seems to be slow. I find many loops in your code. Can it speed up ? Or any suggestion?

Best,

**Comment by SteveJunGao** [comment]
We have an optimized version, please check it here: https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/renderers/DIB-R/graphics

**Comment by hungsing92** [comment]
Thanks for your quick reply!

 I have tried this version. It costs 200ms to render one picture, but [tf_mesh_renderer](https://github.com/google/tf_mesh_renderer) just costs 20ms. It seems that there is some difference between your pipeline. 

Best,

**Comment by wenzhengchen** [comment]
We re-write OpenGL by cuda in PyTorch, and that's why it is slower than directly calling OpenGL. We are preparing a faster version.

**Comment by jli113** [comment]
Page not found at 
https://github.com/NVIDIAGameWorks/kaolin/tree/master/examples/renderers/DIB-R/graphics
